get:
  tags:
    - Authorization
  security: []
  summary: OpenID Connect Discovery
  description: Returns metadata that covers endpoint locations, server capabilities and configuration.
  operationId: discoverOpenIDConfiguration
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ..\components\schemas\WellKnown.yaml
    '500':
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: ..\components\schemas\ErrorResponse.yaml
