openapi: 3.0.1
info:
  title: bvnid
  version: 0.0.1
  description: Electronic identification solution for proof of identity of citizens for services, such as payment and digital signature.
servers:
  - url: 'https://${request.url.host}:${request.url.port}/'
    variables:
      request.url.host:
        default: unknown
      request.url.port:
        default: unknown
paths:
  /authorize:
    $ref: paths\authorize.yaml
  /token:
    $ref: paths\token.yaml
  /.well-known/openid-configuration:
    $ref: paths\.well-known@openid-configuration.yaml
  /jwks.json:
    $ref: paths\jwks.json.yaml
  /userinfo:
    $ref: paths\userinfo.yaml
components:
  securitySchemes:
    BasicAuth:
      $ref: components\securitySchemes\basic.yaml
    BearerAuth:
      $ref: components\securitySchemes\bearer.yaml