openapi: 3.0.1
info:
  title: bvnid
  version: 0.0.1
  description: Electronic identification solution for proof of identity of citizens for services, such as payment and digital signature.
servers:
  - url: 'http://www.bvnid.com/auth'
    description: BVNID server
paths:
  /authorize:
    $ref: paths\authorize.yaml
  /token:
    $ref: paths\token.yaml
  /.well-known/openid-configuration:
    $ref: paths\.well-known@openid-configuration.yaml
  /jwks.json:
    $ref: paths\jwks.json.yaml
  /userinfo:
    $ref: paths\userinfo.yaml
components:
  securitySchemes:
    clientSecretBasic:
      type: http
      description: basic authentication with client_id and client_secret
      scheme: basic
    BearerAuth:
      type: http
      description: Token authentication
      scheme: bearer